version: "3.7"

services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    ports:
      - "8080:8080"
    networks:
      - s-network

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      POSTGRES_DB: gmtek
    ports:
      - "27017:27017"
    networks:
      - s-network
    volumes:
      - mongo_data:/data/db

networks:
  s-network:
    driver: bridge

volumes:
  mongo_data:
